name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.14=py310h853098b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h237132a_0
  - libcxx=20.1.7=ha82da77_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - liblzma=5.8.1=h39f12f2_2
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.2=h6fb428d_0
  - libzlib=1.3.1=h8359307_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.1=h81ee809_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310h078409c_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h6cefb37_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=7_cp310
  - pyzmq=27.0.0=py310h6d25ecc_0
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.1=py310h078409c_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==4.0.3
      - attrs==25.3.0
      - bleach==6.0.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - faiss-cpu==1.11.0
      - frozenlist==1.7.0
      - gunicorn==20.1.0
      - gurobipy==12.0.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - jiter==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.1.8
      - langchain-community==0.0.27
      - langchain-core==0.1.53
      - langsmith==0.1.147
      - markdown==3.4.1
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - multidict==6.6.3
      - mypy-extensions==1.1.0
      - numpy==1.26.4
      - openai==1.93.0
      - orjson==3.10.18
      - packaging==23.2
      - pandas==2.3.0
      - propcache==0.3.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dotenv==0.19.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - tenacity==8.5.0
      - tiktoken==0.9.0
      - tqdm==4.67.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - webencodings==0.5.1
      - werkzeug==2.2.3
      - yarl==1.20.1
prefix: /Users/xue/miniforge3/envs/test
